salesforce_oauth.salesforce_oauth_config.*:
  type: config_entity
  label: 'Salesforce OAuth Config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
      translatable: true
    consumer_key:
      type: string
      label: 'Consumer Key'
    consumer_key:
      type: string
      label: 'Consumer Secret'
    login_url:
      type: uri
      label: 'Login URL'
