<?php

/**
 * @file
 * Contains salesforce_example.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function salesforce_example_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the salesforce_example module.
    case 'help.page.salesforce_example':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Salesforce Examples') . '</p>';
      return $output;

    default:
  }
}
