<?php

/**
 * @file
 * Contains salesforce_logger.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function salesforce_logger_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the salesforce_example module.
    case 'help.page.salesforce_logger':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Salesforce Logger') . '</p>';
      return $output;

    default:
  }
}
