<?php

use Drupal\Core\Entity\EntityInterface;
use Drupal\encrypt\EncryptionProfileInterface;
use Drupal\salesforce\EntityNotFoundException;

/**
 * Implements hook_encryption_profile_predelete()
 * If the assigned Encryption profile gets deleted, reset encryption settings.
 */
function salesforce_encryption_profile_predelete(EncryptionProfileInterface $entity) {
  \Drupal::service('salesforce.client')->hookEncryptionProfileDelete($entity);
}
