salesforce_jwt.salesforce_jwt_auth_config.*:
  type: config_entity
  label: 'Salesforce JWT Auth Config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
      translatable: true
    consumer_key:
      type: string
      label: 'Consumer Key'
    login_user:
      type: string
      label: 'Login User'
    login_url:
      type: uri
      label: 'Login URL'
    encrypt_key:
      type: key.key.[%key]
      label: 'Encryption Key ID'
