<?php

/**
 * @file
 * Pull updates from Salesforce when a Salesforce object is updated.
 */

use Drupal\salesforce\Rest\RestClient;
use Drupal\salesforce_pull\QueueHandler;
use Drupal\salesforce_pull\DeleteHandler;
use Psr\Log\LoggerTrait;

/**
 * Implements hook_cron().
 */
function salesforce_pull_cron() {
  $sfapi = \Drupal::service('salesforce.client');
  if ($sfapi->isAuthorized()) {
    QueueHandler::create(
      $sfapi,
      \Drupal::service('entity.manager')
        ->getStorage('salesforce_mapping')
        ->loadMultiple(),
      \Drupal::queue('cron_salesforce_pull'),
      \Drupal::service('event_dispatcher'),
      \Drupal::request(),
      \Drupal::logger('Salesforce Pull')
    )->getUpdatedRecords();
    DeleteHandler::create(
      $sfapi,
      \Drupal::service('entity_type.manager'),
      \Drupal::state(),
      \Drupal::logger('Salesforce Pull')
    )->processDeletedRecords();
  }
}
