<?php

/**
 * @file
 * Pull updates from Salesforce when a Salesforce object is updated.
 */

use Drupal\salesforce\Rest\RestClient;
use Drupal\salesforce_pull\QueueHandler;
use Drupal\salesforce_pull\DeleteHandler;

/**
 * Implements hook_cron().
 */
function salesforce_pull_cron() {
  $sfapi = salesforce_get_api();
  if ($sfapi->isAuthorized()) {
    QueueHandler::create($sfapi)
      ->getUpdatedRecords();
    DeleteHandler::processDeletedRecords($sfapi);
  }
}
